owner: Nugrahmuhammad
repo: uptime-monitor

sites:
  - name: CG
    url: ${{ secrets.SECRET_API_URL }}
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com

status-website:
  baseUrl: /
  name: Uptime Monitor
  introTitle: "📡 Status Layanan"
  introMessage: "Monitoring otomatis menggunakan **Upptime**"

notifications:
  - type: discord
    env:
      NOTIFICATION_DISCORD: true
      NOTIFICATION_DISCORD_WEBHOOK: true
      NOTIFICATION_DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

env:
  NOTIFICATIONS_DOWN_MESSAGE: "🚨 $SITE_NAME ($SITE_URL) DOWN! Code: $RESPONSE_CODE → $ISSUE_URL"
  NOTIFICATIONS_UP_MESSAGE: "✅ $SITE_NAME sudah kembali normal."
