# Change these first
owner: Nugrahmuhammad
repo: uptime-monitor


sites:
  - name: CG
    url: ${{ secrets.SECRET_API_URL }}

status-website:
  # cname: demo.upptime.js.org   <-- ini hapus kalau tidak pakai domain sendiri
  baseUrl: /uptime-monitor       # pakai nama repo kamu
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime Monitor           # ganti nama sesuai keinginan
  introTitle: "**Uptime Monitor** untuk proyek saya"
  introMessage: Halaman status otomatis dari [repo GitHub](https://github.com/Nugrahmuhammad/uptime-monitor). Tidak perlu server tambahan — hanya Actions, Issues, dan Pages.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/Nugrahmuhammad/uptime-monitor

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
