name: Uptime Monitor

on:
  schedule:
    - cron: "*/5 * * * *" # cek setiap 5 menit
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Upptime
        run: npm install -g upptime

      - name: Run Uptime Checks
        id: uptime
        run: |
          RESULT=$(npx upptime check-all || echo "down")
          echo "status=$RESULT" >> $GITHUB_OUTPUT

      - name: Notify if down
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
            -d '{"content":"🚨 Beberapa website terdeteksi DOWN"}' \
            ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Notify if up
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
            -d '{"content":"✅ Semua website sudah UP kembali"}' \
            ${{ secrets.DISCORD_WEBHOOK_URL }}
